workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.cocoapods/repos
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Generate iOS icons
        script: |
          flutter pub run flutter_launcher_icons
      - name: Generate iOS splash
        script: |
          flutter pub run flutter_native_splash:create
      - name: Install pods
        script: |
          cd ios && pod install
      - name: Build iOS IPA
        script: |
          flutter build ipa \
            --release \
            --build-name=1.0.3 \
            --build-number=4 \
            --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com