-- Create categories table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_en TEXT NOT NULL UNIQUE,
    name_ar TEXT NOT NULL,
    parent_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users only" ON public.categories FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users only" ON public.categories FOR UPDATE USING (auth.role() = 'authenticated');
CREATE POLICY "Enable delete for authenticated users only" ON public.categories FOR DELETE USING (auth.role() = 'authenticated');

-- Insert default categories if they don't exist
INSERT INTO public.categories (name_en, name_ar, parent_id)
VALUES 
    ('Lahm Bi Ajeen', 'لحم بعجين', NULL),
    ('Pizza', 'بيتزا', NULL),
    ('Drinks', 'مشروبات', NULL)
ON CONFLICT (name_en) DO NOTHING;
