@echo off
echo Pulling latest changes from GitHub...
git pull origin main --rebase
echo Adding ALL files...
git add .
echo Committing...
git commit -m "تحديث إصدار التطبيق (1.0.2+3) وتحديث ملفات بناء الويندوز والأندرويد للإنتاج"
echo Pushing...
git push origin main
echo Done!
pause
